# Generated by Django 6.0.5 on 2026-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
